language: node_js

env:
  - DB=postgresql://postgres@localhost:5432/greet_db_test

node_js:
  - "12"

before_script: 
  - psql -c 'create database greet_db_test;' -U postgres
  - psql -U postgres -d greet_db_test -a -f database.sql

addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5